name: Deploy to Tomcat

on:
  push:
    branches:
      - '**'  # Change this to your main branch name
  pull_request:
    branches:
      - '**'  # Change this to your main branch name
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Set the Java version you need
    
    - name: Build Maven app
      run: mvn clean package

    - name: Deploy to Tomcat
      run: |
        cp target/*.war $CATALINA_HOME/webapps/
        $CATALINA_HOME/bin/startup.sh
